### ISSUE TITLE
Add enter() and exit() functions

### ISSUE THREAD

**Issue by andyjansson** [jonathantneal/postcss-visitor#2]
Parsers such as babel have [visitors which define `enter()` and `exit()`](https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/plugin-handbook.md#visitors) callbacks. Adding `enter()`and `exit()` would enable plugins to register callbacks on both pre-order and post-order traversal. 

```js
{
  decl: {
     enter(node, result) {
        // do something when entering a declaration
     },
     exit(node, result) {
        // do something when exiting a declaration
     }
  }
}
```

**Comment by jonathantneal** [comment]
Thanks for looking into this, @andyjansson.

Right now, the walker first [visits the current node](https://github.com/jonathantneal/postcss-visitor/blob/master/lib/walk.js#L26-L29) before it [walks its children](https://github.com/jonathantneal/postcss-visitor/blob/master/lib/walk.js#L84-L94).

It looks like I just need to make that first visitation the `enter()` method, which allows the object-less shorthand. Then, after it walks the children, run the `exit()` method. I’ll add this.

**Comment by jonathantneal** [comment]
Resolved via https://github.com/jonathantneal/postcss-visitor/commit/ac327ae8b7b7038d318ef97584e5e5dfbc2ddf56
